### ISSUE TITLE
Project Timeline and Planning

### ISSUE THREAD

**Issue by Vidmaster** [Vidmaster/cybr8950-quantum#10]
An important part of project planning is identifying tasks to be completed to address project goals and arranging those tasks in such a way that they can be completed within a (typically) fixed interval of time. In this class, that interval is the length of the semester. For milestone one, prepare an overall project timeline that identifies large tasks to be completed, estimates time of completion, and arranges those tasks chronologically over the project lifespan.

Submission materials
You should create a project (Kanban) board on GitHub and the create task cards that identify major tasks that span the rest of the semester. You can read more about the GitHub Project feature here: https://docs.github.com/en/github/managing-your-work-on-github/about-project-boards

**Comment by ZexiXin** [comment]
This part has been done mostly.

**Comment by ZexiXin** [comment]
Timeline and Gantt chart has been done at this moment
