### ISSUE TITLE
Project Risk List

### ISSUE THREAD

**Issue by Vidmaster** [Vidmaster/cybr8950-quantum#11]
As you will probably discover, there are many things that can go wrong when working on a project. Issues with skillsets, technology, team member availability, etc, may arise as the project goes forward. As we discussed in class, there are three options available to deal with project management risks: monitor it (Watch it), mitigate it (do something about it), accept it (give up). For milestone one, you should identify the major sources of risk and what you plan to do about them. Prepare a risk list and rank them by risk level using the standard formula, i.e. impact x likelihood, to describe the top 5 risks that might affect your team's ability to pull off the tasks identified in your timeline and dictated by your objectives.

Submission materials
You should prepare a risk list table and add it to your README.md file in your GitHub project repo, beneath your Gantt chart.

**Comment by caseyschmitz** [comment]
Some risks that were collaboratively identified during 02/04 team call:
- team member availability
- learning curve associated with quantum computing
    - the learning "rabbit holes" that could distract efforts from the core problem
- infrastructure availability/capabilities
