### ISSUE TITLE
Literature Review - Current Cryptographic Protocols

### ISSUE THREAD

**Issue by Vidmaster** [Vidmaster/cybr8950-quantum#17]
For milestone 1, you should prepare a literature review document that surveys the various research and development work in your project area. Your literature review should identify important keywords, relevant research papers, and the state of the art in your area.

This task is focused on identifying sources related to currently used classical cryptographic protocols and their implementations, specifically as relates to confidentiality, integrity, and non-repudiation of messages. Identify sources and create a structured abstract for each, following the guidelines here: https://unomaha.instructure.com/courses/43651/pages/introduction-to-research-process

**Comment by ZexiXin** [comment]
BB84, E91, B92, BBM92, Six-State-protocol, DPS protocol, SARG04 Protocol, COW, and S13.
