### ISSUE TITLE
Continued Research

### ISSUE THREAD

**Issue by caseyschmitz** [Vidmaster/cybr8950-quantum#46]
Identify and fill gaps in M1's [Literature Review](https://github.com/Vidmaster/cybr8950-quantum/blob/main/LiteratureReview.md).

**Comment by ZexiXin** [comment]
Your outline will not be graded using a rubric, but it is expected to meet the following requirements.

1. Contains a well-written 500 word or less abstract that previews the argument to be made in the paper.
2. Has defined section headings for each of the sections you expect to have in your paper
3. Has a bulleted list of talking points you expect to fall within each section
4. Section headings and bullets build a narrative flow that is compatibile with your main research argument.

**Comment by ZexiXin** [comment]
Researching of M2 has been accomplished

**Comment by ZexiXin** [comment]
Researching of M2 has been accomplished
