### ISSUE TITLE
Diagrams

### ISSUE THREAD

**Issue by caseyschmitz** [Vidmaster/cybr8950-quantum#47]
[Visual Understanding / Diagrams](https://github.com/MLHale/CYBR4580-8950/blob/master/projects/milestone2.md#diagrams)

Develop some diagrams for the project.

**Comment by ZexiXin** [comment]
Produce a set of process or conceptual diagrams suited to your project. This could be a set of activity diagrams for penetration-testing oriented projects, it could be software architecture diagrams for development-oriented projects, or it could be a process/conceptual model for other projects.
