### ISSUE TITLE
M2 Presentation

### ISSUE THREAD

**Issue by caseyschmitz** [Vidmaster/cybr8950-quantum#54]
Google Slides presentation created [here](https://docs.google.com/presentation/d/13ZV0zqzMfeveeJ817WCpkaR2oRiBfZtVhS9bGXdIBvA/edit?usp=sharing).

We can collaboratively work on the presentation before converting to ppt for final presentation.

Presentation guidelines [here](https://github.com/MLHale/CYBR4580-8950/blob/master/projects/milestone2.md#presentation).

**Comment by ZexiXin** [comment]
Presentation has been recorded on 04/01/2021
